version: "3.7"

services:
  php:
    volumes: &appvolumes-linux
      - ./src:/var/www/html:delegated
      - ../../.composer:/var/www/.composer:delegated
      - ../../.composer:/var/www/html/var/composer_home:delegated
      - ./ctx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated

  php_without_xdebug:
    volumes: &appvolumes-linux
      - ./src:/var/www/html:delegated
      - ./ctx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated

  nginx:
    volumes: *appvolumes-linux

  node:
    volumes: *appvolumes-linux