version: "3.7"

services:
  php:
    build:
      dockerfile: ./ctx/php.Dockerfile
    volumes:
      - filesdata:/var/www/html
      #- composercache:/var/www/html/var/composer_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

  nginx:
    build:
      dockerfile: ./ctx/nginx.Dockerfile
    volumes:
      - ./src:/var/www/html:cached
      - ./ctx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "{{{NGINX_PROJECT_PORT}}}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - php
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

volumes:
  filesdata:
  #composercache:
    #external: true