version: "3.7"
services:
  nginx:
    build:
      context: ctx
      dockerfile: nginx.Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ./data/nginx/:/var/log/nginx
    ports:
      - "{{{NGINX_PORT}}}:80"
    depends_on:
      - php
    networks:
      app_net:

  php:
    build:
      context: ctx
      dockerfile: php.Dockerfile
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - db
    networks:
      app_net:

  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    build:
      context: ctx
      dockerfile: db.Dockerfile
    volumes:
      - ./data/mysql/:/var/lib/mysql/
    networks:
      app_net:

  elasticsearch:
    build:
      context: ctx
      dockerfile: elasticsearch.Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    networks:
      app_net:

  redisdb:
    build:
      context: ctx
      dockerfile: redis.Dockerfile
    networks:
      app_net:

networks:
  app_net:
    external: true
    name: aruntime_madock_general_net
