version: "3.7"
services:
  nginx:
    build:
      context: ctx
      dockerfile: nginx.Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "{{{NGINX_PROJECT_PORT}}}:80"
    depends_on:
      - php
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

  php:
    build:
      context: ctx
      dockerfile: php.Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ../../.composer:/var/www/.composer
      - ../../.composer:/var/www/html/var/composer_home
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    build:
      context: ctx
      dockerfile: db.Dockerfile
    volumes:
      - ./data/mysql/:/var/lib/mysql
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

  node:
    build:
      context: ctx
      dockerfile: node.Dockerfile
    ports:
      - 35729:35729
    volumes:
      - ./src/:/var/www/html/
    profiles:
      - node{{{NODEJS_ENABLE}}}
    depends_on:
      - php

  elasticsearch:
    build:
      context: ctx
      dockerfile: elasticsearch.Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_vlm:/usr/share/elasticsearch/data
    profiles:
      - elasticsearch{{{ELASTICSEARCH_ENABLE}}}
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

  redisdb:
    build:
      context: ctx
      dockerfile: redis.Dockerfile
    profiles:
      - redisdb{{{REDIS_ENABLE}}}
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

  rabbitmq:
    image: rabbitmq:{{{RABBITMQ_VERSION}}}
    profiles:
      - rabbitmq{{{RABBITMQ_ENABLE}}}
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: "http://{{{HOST_NAME_DEFAULT}}}/phpmyadmin/"
    ports:
      - "{{{NGINX_PROJECT_PORT+1}}}:80"
    depends_on:
      - db
    networks:
      app_net_{{{NETWORK_NUMBER}}}:

volumes:
  elasticsearch_vlm:
networks:
  app_net_{{{NETWORK_NUMBER}}}:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.{{{NETWORK_NUMBER}}}.0/24
