version: "3.7"

services:
  php:
    volumes: &appvolumes-windows

  php_without_xdebug:
    volumes: &appvolumes-windows

  nginx:
    volumes: *appvolumes-windows

  node:
    volumes: *appvolumes-windows