version: "3.7"
services:
  php:
    build:
      context: ctx
      dockerfile: php.Dockerfile
    volumes: &appvolumes
      - ./ctx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: ctx
      dockerfile: nginx.Dockerfile
    ports:
      - "{{{NGINX_PROJECT_PORT}}}:80"
      - "{{{NGINX_PROJECT_PORT_SSL}}}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - php

  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    build:
      context: ctx
      dockerfile: db.Dockerfile
    volumes:
      - dbdata:/var/lib/mysql
      - ./ctx/my.cnf:/etc/mysql/conf.d/mysql.cnf:delegated

  node:
    build:
      context: ctx
      dockerfile: node.Dockerfile
    volumes: *appvolumes
    profiles:
      - node{{{NODEJS_ENABLE}}}
    depends_on:
      - php

  elasticsearch:
    build:
      context: ctx
      dockerfile: elasticsearch.Dockerfile
    deploy:
      resources:
        limits:
          memory: 2512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms800m -Xmx800m"
    volumes:
      - elasticsearch_vlm:/usr/share/elasticsearch/data
    profiles:
      - elasticsearch{{{ELASTICSEARCH_ENABLE}}}

  redisdb:
    build:
      context: ctx
      dockerfile: redis.Dockerfile
    profiles:
      - redisdb{{{REDIS_ENABLE}}}

  rabbitmq:
    image: rabbitmq:{{{RABBITMQ_VERSION}}}
    profiles:
      - rabbitmq{{{RABBITMQ_ENABLE}}}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    environment:
      PMA_HOST: "db"
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: "http://{{{HOST_NAME_DEFAULT}}}/phpmyadmin/"
      PMA_USER: root
      PMA_PASSWORD: {{{DB_ROOT_PASSWORD}}}
      UPLOAD_LIMIT: 1G
    ports:
      - "{{{NGINX_PROJECT_PORT+2}}}:80"
    depends_on:
      - db

volumes:
  dbdata:
  elasticsearch_vlm:
