version: "3.7"

services:
  phpfpm:
    volumes: &appvolumes-mac
      - workspace:/var/www/html
      - ./src/app:/var/www/html/app:delegated
      - ./src/.git:/var/www/html/.git:delegated
      - ./src/composer.json:/var/www/html/composer.json:delegated
      - ./src/composer.lock:/var/www/html/composer.lock:delegated
      # {FILES_IN_GIT}

  nginx:
    volumes: *appvolumes-mac

  node:
    volumes: *appvolumes-mac

  unison:
    build:
      dockerfile: ./ctx/unison.Dockerfile
    volumes:
      - workspace:/var/www/html
      - ./src/vendor:/sync/vendor
    environment:
      - SYNC_SOURCE_BASE_PATH=/sync
      - SYNC_DESTINATION_BASE_PATH=/var/www/html
      - SYNC_MAX_INOTIFY_WATCHES=60000
    depends_on:
      - php
    privileged: true

volumes:
  workspace: