version: "3.7"
services:
  nginx:
    build:
      dockerfile: ./ctx/Dockerfile
    volumes:
      - ./ctx/proxy.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"