version: "3.7"
services:
  nginx:
    build:
      context: ctx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/:/var/log/nginx
    networks:
      madock_general_net:

networks:
  madock_general_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.90.0/24
