version: "3.7"
services:
  nginx:
    build:
      context: ctx
      dockerfile: Dockerfile
    volumes:
      - ./ctx/proxy.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - madock

networks:
  madock: